# Generated by Django 5.0.3 on 2024-03-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockZcw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('house', models.CharField(max_length=10, null=True, blank=True, default='')),
                ('name', models.CharField(max_length=10, null=True, blank=True, default='')),
                ('price', models.FloatField(default=0)),
                ('buy_price', models.FloatField(default=0)),
                ('stop_surplus', models.FloatField(default=0)),
                ('stop_loss', models.FloatField(default=0)),
                ('zdf', models.FloatField(default=0)),
                ('hsl', models.FloatField(default=0)),
                ('syl', models.FloatField(default=0)),
                ('sjl', models.FloatField(default=0)),
                ('zsz', models.FloatField(default=0)),
                ('ltsz', models.FloatField(default=0)),
            ],
        ),
    ]
