# Generated by Django 5.0.3 on 2024-03-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockzcw',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stockzcw',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
