# Generated by Django 5.0.3 on 2024-03-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockModel', '0002_stockzcw_create_time_stockzcw_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('house', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('event_remark', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('event_time', models.DateTimeField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
