# Generated by Django 5.0.3 on 2024-03-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockModel', '0004_remove_stockevents_house_remove_stockevents_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockevents',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stockevents',
            name='update_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stockzcw',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stockzcw',
            name='update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
