# Generated by Django 5.0.3 on 2024-03-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockModel', '0005_alter_stockevents_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockevents',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
