# Generated by Django 5.0.3 on 2024-03-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockModel', '0006_alter_stockevents_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockevents',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
