# Generated by Django 5.0.3 on 2024-03-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockModel', '0007_alter_stockevents_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockConcepts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('sort', models.IntegerField(default=0)),
                ('stocks', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('create_time', models.DateTimeField(null=True)),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
