# Generated by Django 5.0.3 on 2024-03-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockModel', '0008_stockconcepts'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockOpportunity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('text', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('sort', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
