# Generated by Django 5.0.3 on 2024-04-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockModel', '0009_stockopportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockCycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
