# Generated by Django 5.0.3 on 2024-04-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockModel', '0010_stockcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockzcw',
            name='lb',
            field=models.FloatField(default=0),
        ),
    ]
